### ISSUE TITLE
Getting Started help needed

### ISSUE THREAD

**Issue by shandhamankar** [myflashlab/videoPlayer-ANE#16]
Hi,

I just purchased a license from your website and need some help getting started for my iOS App.

I'm using Animate CC with Air23 for iOS. My question is I have 3 buttons on my app home screen and I want each of them to play a video bundled with the app.

Is there a similar sample project that can hep me or if you could guide me how to achieve this.

Also is there a detailed documentation for this ANE that we can refer to?

Thanks,
Shaan.

**Comment by myflashlab** [comment]
working with this ANE is very simple, first [embed the ANE in your project](https://www.youtube.com/playlist?list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O) and then check out the sample code https://github.com/myflashlab/videoPlayer-ANE/blob/master/FD/src/MainFinal.as

**Comment by myflashlab** [comment]
Please let us know if you have any question?

**Comment by shandhamankar** [comment]
Hi,

I've checked the documentation links shared in your previous comment, however I need some simple and specific help.

1. I need to load different local videos on different button placed on the stage.
2. I want to be able to play all video continuous one after another on an additional button that reads 'Play All Videos'.

I can share a file structure to help understand my exact need if this is unclear.
Would really appreciate a quick response.

Thanks in advance,
Shaan.

**Comment by shandhamankar** [comment]
Still waiting for you to reply...

**Comment by myflashlab** [comment]
oops, missed this! sorry. Well, playing different video files is the main job of the ANE as shown in the demo project. So I'm not sure what other instruction I can give rather than what is included in the demo project. If you are facing a specific problem though, let us know and we will help.

But in regard to your other question about playing several videos one after the other, well, that could be tricky because videos are being played in external apps and the AIR side can't know when the video is finished... Maybe you should have a look at our [Embedded video player?](http://www.myflashlabs.com/product/surface-embedded-video-player-ane/)

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
