### ISSUE TITLE
android video issue

### ISSUE THREAD

**Issue by wigginsray** [myflashlab/videoPlayer-ANE#23]
Trying to play video - works fine for the "ON_LINE" version of the video. 

My code checks to see if video is in the applicationStorageDirectory, if exists then play the local video. 
In my test, the video is found

Debugging it returns the nativepath.
"Playing Local Video:/data/user/0/air.com.xxxxxxx/com.xxxxxxx/Local Store/www/videos/Video-File.mp4"

On the device the video player launches, but gives the following message:
"Failed to play video. An unknown error has occurred."

```

		private function videoPlayLocalFile(videoName){
			trace("Playing Local Video:"+videoName.nativePath);
			var _ex:VideoPlayer = new VideoPlayer();
			_ex.play(videoName.nativePath, VideoType.ON_SD_CARD);
			
		}
		
		private function videoPlayRemoteFile(videoURL){
			trace("Playing Remote Video:"+videoURL);
			var _ex:VideoPlayer = new VideoPlayer();
			_ex.play(videoURL, VideoType.ON_LINE);
		}
		
		private function videoPlayLocalOrWeb(videoName,videoURL){
			var videoFileReference:File = File.applicationStorageDirectory.resolvePath("www/videos/"+videoName);
			if (videoFileReference.exists){
				videoPlayLocalFile(videoFileReference);
			}else{
				videoPlayRemoteFile(videoURL);
			}
		}
```

**Comment by PippoApps** [comment]
From the docs it seems only files in the cache folder can be played on Android.

**Comment by myflashlab** [comment]
Before ```targetSdkVersion 26```, we could use the ```WRITE_EXTERNAL_STORAGE``` permission and the ANE could start an intent to play the video on ```File.documentsDirectory```.

But Android has changed these rules since ```targetSdkVersion 26```. Considering that you are not allowed to use any targetSdkVersion lower than 26, we updated the ANE permanently to work with the new Android suggested workaround.

The current practice with this ANE and similar ones, like the PDF ANE, is to let other apps on the device have access to a specific location inside the cache directory. This is what Android calls, ```provider```. 

So, instead of using the ```WRITE_EXTERNAL_STORAGE``` permission, we must put the video file in the cache folder of our AIR app where we have provided the access to that location from other video player apps on the device.

It may seem like a limitation but I really think this is a very good move by Android and it will help Android apps be more secure in future. If you compare this with the iOS side, Apple has been doing a better job since the beginning but Android is trying to do similar stuff (at least in this specific field) with a little different.

**Comment by PippoApps** [comment]
Ok, so the solution would be to reference the file, copy it in the cache folder, then play it right?
Thank you

**Comment by myflashlab** [comment]
yes, at least for now. If we found a better solution working with AIR, we'll update the ANE.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
